name: node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2.3.4
        
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '14.15'

      - name: Install everything
        run: npm install --include=dev
      
      - name: npm test
        run: npm test

